#name: visualsace
#pygments: true
#paginate: 5
#url: http://boombo.github.io/boombo
#baseurl: http://boombo.github.io/boombo
#paginate_path: page/:num
#markdown: rdiscount
#permalink: pretty

gems: [jekyll-paginate]
name: visualsace
#pygments: true
highlighter: rouge
paginate: 5
paginate_path: page/:num
#baseurl: /boombo
baseurl: http://www.visualsace.fr
markdown: kramdown
permalink: pretty
url: http://www.visualsace.fr