#name: visualsace
#pygments: true
#paginate: 5
#url: http://boombo.github.io/boombo
#baseurl: http://boombo.github.io/boombo
#paginate_path: page/:num
#markdown: rdiscount
#permalink: pretty

name: visualsace
pygments: true
paginate: 5
paginate_path: page/:num
baseurl: /boombo
markdown: rdiscount
permalink: pretty
pygments: true
url: http://visualsace.fr